project:
  type: website
  output-dir: docs

website:
  title: "Journey into Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: https://drive.google.com/file/d/12J3FZfsy0TACJuAu0YxLcFJPfC9afZtJ/view?usp=sharing
        text: Resume

format:
  html:
    theme: 
      dark: lux #darkly or slate
      light: lux
    css: styles.css
    toc: true

babelquarto:
  languagecodes:
    - name: en
      text: "English"
    - name: es
      text: "Spanish"
  mainlanguage: 'en'
  languages: ['en', 'es']

title-en: "Journey into Data Science"
title-es: "Ciencia de Datos"
lang: en
