project:
  type: website
  output-dir: docs

website:
  title: "Journey into Data Science"
  back-to-top-navigation: true
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: https://drive.google.com/file/d/12J3FZfsy0TACJuAu0YxLcFJPfC9afZtJ/view?usp=sharing
        text: Resume
  page-footer:
    background: black
    center: 
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/nicotertu/
      - icon: github
        aria-label: GitHub
        href: https://github.com/Nicotertu
      - icon: envelope
        aria-label: Resume
        href: https://drive.google.com/file/d/12J3FZfsy0TACJuAu0YxLcFJPfC9afZtJ/view?usp=drive_link

format:
  html:
    theme:
      #dark: [lux, theme-dark.scss]
      light: [lux, theme-light.scss]
    css: styles.css
    toc: true
    toc-title: "Jump To"
    code-link: true
    code-tools:
      source: false
      toggle: true
    code-block-bg: true
    code-line-numbers: true
    highlight-style: github
    code-block-border-left: true
    grid: 
      sidebar-width: 0px #250px
      body-width: 1600px #1400px
      margin-width: 300px
      gutter-width: 5% #3.5em

#cap-location: margin
#fig-cap-location: margin
#tbl-cap-location: margin
#tbl-column: screen-inset-left

babelquarto:
  languagecodes:
    - name: en
      text: "English"
    - name: es
      text: "Spanish"
  mainlanguage: 'en'
  languages: ['en', 'es']

title-en: "Journey into Data Science"
title-es: "Ciencia de Datos"
lang: en
